###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: phpdev-memcached

    redis:
      image: redis:alpine
      container_name: phpdev-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: phpdev-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=devpasswd
        - POSTGRES_DB=devdb

    webserver:
      image: nginx:alpine
      container_name: phpdev-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpdev-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

